name: simplexmq
version: 3.0.0
synopsis: SimpleXMQ message broker
description: |
  This package includes <./docs/Simplex-Messaging-Server.html server>,
  <./docs/Simplex-Messaging-Client.html client> and
  <./docs/Simplex-Messaging-Agent.html agent> for SMP protocols:
  .
  * <https://github.com/simplex-chat/simplexmq/blob/master/protocol/simplex-messaging.md SMP protocol>
  * <https://github.com/simplex-chat/simplexmq/blob/master/protocol/agent-protocol.md SMP agent protocol>
  .
  See <https://github.com/simplex-chat/simplex-chat terminal chat prototype> built with SimpleXMQ broker.

homepage: https://github.com/simplex-chat/simplexmq#readme
license: AGPL-3
author: simplex.chat
maintainer: chat@simplex.chat
copyright: 2020-2022 simplex.chat
category: Chat, Network, Web, System, Cryptography
extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - aeson == 2.0.*
  - ansi-terminal >= 0.10 && < 0.12
  - asn1-encoding == 0.9.*
  - asn1-types == 0.3.*
  - async == 2.2.*
  - attoparsec == 0.14.*
  - base >= 4.14 && < 5
  - base64-bytestring >= 1.0 && < 1.3
  - bytestring == 0.10.*
  - case-insensitive == 1.2.*
  - composition == 1.0.*
  - constraints >= 0.12 && < 0.14
  - containers == 0.6.*
  - cryptonite >= 0.27 && < 0.30
  - cryptostore == 0.2.*
  - data-default == 0.7.*
  - direct-sqlite == 2.3.*
  - directory == 1.3.*
  - filepath == 1.4.*
  - http-types == 0.12.*
  - http2 == 3.0.*
  - generic-random >= 1.3 && < 1.5
  - ini == 0.4.*
  - iso8601-time == 0.1.*
  - memory == 0.15.*
  - mtl == 2.2.*
  - network >= 3.1.2.7 && < 3.2
  - network-transport == 0.5.*
  - optparse-applicative >= 0.15 && < 0.17
  - QuickCheck == 2.14.*
  - process == 1.6.*
  - random >= 1.1 && < 1.3
  - simple-logger == 0.1.*
  - sqlite-simple == 0.4.*
  - stm == 2.5.*
  - template-haskell == 2.16.*
  - text == 1.2.*
  - time == 1.9.*
  - time-compat == 1.9.*
  - time-manager == 0.0.*
  - tls >= 1.5.7 && < 1.6
  - transformers == 0.5.*
  - unliftio == 0.2.*
  - unliftio-core == 0.2.*
  - websockets == 0.12.*
  - x509 == 1.7.*
  - x509-store == 1.6.*
  - x509-validation == 1.6.*

flags:
  swift:
    description: Enable swift JSON format
    manual: True
    default: False

when:
  - condition: flag(swift)
    cpp-options:
      - -DswiftJSON

library:
  source-dirs: src

executables:
  smp-server:
    source-dirs: apps/smp-server
    main: Main.hs
    dependencies:
      - simplexmq
    ghc-options:
      - -threaded

  ntf-server:
    source-dirs: apps/ntf-server
    main: Main.hs
    dependencies:
      - simplexmq
    ghc-options:
      - -threaded

  smp-agent:
    source-dirs: apps/smp-agent
    main: Main.hs
    dependencies:
      - simplexmq
    ghc-options:
      - -threaded

tests:
  smp-server-test:
    source-dirs: tests
    main: Test.hs
    dependencies:
      - simplexmq
      - hspec == 2.7.*
      - hspec-core == 2.7.*
      - HUnit == 1.6.*
      - QuickCheck == 2.14.*
      - timeit == 2.0.*

ghc-options:
  # - -haddock
  - -Wall
  - -Wcompat
  - -Werror=incomplete-patterns
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wunused-type-patterns
