name: simplexmq
version: 6.1.0.1
synopsis: SimpleXMQ message broker
description: |
  This package includes <./docs/Simplex-Messaging-Server.html server>,
  <./docs/Simplex-Messaging-Client.html client> and
  <./docs/Simplex-Messaging-Agent.html agent> for SMP protocols:
  .
  * <https://github.com/simplex-chat/simplexmq/blob/master/protocol/simplex-messaging.md SMP protocol>
  * <https://github.com/simplex-chat/simplexmq/blob/master/protocol/agent-protocol.md SMP agent protocol>
  .
  See <https://github.com/simplex-chat/simplex-chat terminal chat prototype> built with SimpleXMQ broker.

homepage: https://github.com/simplex-chat/simplexmq#readme
license: AGPL-3
author: simplex.chat
maintainer: chat@simplex.chat
copyright: 2020-2022 simplex.chat
category: Chat, Network, Web, System, Cryptography
extra-source-files:
  - README.md
  - CHANGELOG.md
  - cbits/sha512.h
  - cbits/sntrup761.h
  - apps/smp-server/static/*.html
  - apps/smp-server/static/media/*

dependencies:
  - aeson == 2.2.*
  - ansi-terminal >= 0.10 && < 0.12
  - asn1-encoding == 0.9.*
  - asn1-types == 0.3.*
  - async == 2.2.*
  - attoparsec == 0.14.*
  - base >= 4.14 && < 5
  - base64-bytestring >= 1.0 && < 1.3
  - case-insensitive == 1.2.*
  - composition == 1.0.*
  - constraints >= 0.12 && < 0.14
  - containers == 0.6.*
  - crypton == 0.34.*
  - crypton-x509 == 1.7.*
  - crypton-x509-store == 1.6.*
  - crypton-x509-validation == 1.6.*
  - cryptostore == 0.3.*
  - data-default == 0.7.*
  - direct-sqlcipher == 2.3.*
  - directory == 1.3.*
  - filepath == 1.4.*
  - hashable == 1.4.*
  - hourglass == 0.2.*
  - http-types == 0.12.*
  - http2 >= 4.2.2 && < 4.3
  - ini == 0.4.1
  - iproute == 1.7.*
  - iso8601-time == 0.1.*
  - memory == 0.18.*
  - mtl >= 2.3.1 && < 3.0
  - network >= 3.1.2.7 && < 3.2
  - network-info >= 0.2 && < 0.3
  - network-transport == 0.5.6
  - network-udp >= 0.0 && < 0.1
  - optparse-applicative >= 0.15 && < 0.17
  - process == 1.6.*
  - random >= 1.1 && < 1.3
  - simple-logger == 0.1.*
  - socks == 0.6.*
  - sqlcipher-simple == 0.4.*
  - stm == 2.5.*
  - temporary == 1.3.*
  - time == 1.12.*
  - time-manager == 0.0.*
  - tls >= 1.9.0 && < 1.10
  - transformers == 0.6.*
  - unliftio == 0.2.*
  - unliftio-core == 0.2.*
  - websockets == 0.12.*
  - yaml == 0.11.*
  - zstd == 0.1.3.*

flags:
  swift:
    description: Enable swift JSON format
    manual: True
    default: False
  use_crypton:
    description: Use crypton etc. in cryptostore
    manual: True
    default: True

# cpp-options:
#   - -Dslow_servers

when:
  - condition: flag(swift)
    cpp-options:
      - -DswiftJSON
  - condition: impl(ghc >= 9.6.2)
    dependencies:
      - bytestring == 0.11.*
      - template-haskell == 2.20.*
      - text >= 2.0.1 && < 2.2
  - condition: impl(ghc < 9.6.2)
    dependencies:
      - bytestring == 0.10.*
      - template-haskell == 2.16.*
      - text >= 1.2.3.0 && < 1.3

library:
  source-dirs: src
  c-sources:
    - cbits/sha512.c
    - cbits/sntrup761.c
  include-dirs: cbits
  extra-libraries: crypto

executables:
  smp-server:
    source-dirs:
    - apps/smp-server
    - apps/smp-server/web
    main: Main.hs
    dependencies:
      - file-embed
      - simplexmq
      - wai
      - wai-app-static
      - warp ==3.3.30 # the last one before http2-5.0
      - warp-tls ==3.4.7 # extra internals exposed
    ghc-options:
      - -threaded
      - -rtsopts

  ntf-server:
    source-dirs: apps/ntf-server
    main: Main.hs
    dependencies:
      - simplexmq
    ghc-options:
      - -threaded
      - -rtsopts

  xftp-server:
    source-dirs: apps/xftp-server
    main: Main.hs
    dependencies:
      - simplexmq
    ghc-options:
      - -threaded
      - -rtsopts

  xftp:
    source-dirs: apps/xftp
    main: Main.hs
    dependencies:
      - simplexmq
    ghc-options:
      - -threaded
      - -rtsopts

tests:
  simplexmq-test:
    source-dirs:
    - tests
    - apps/smp-server/web
    main: Test.hs
    dependencies:
      - deepseq == 1.4.*
      - file-embed
      - generic-random == 1.5.*
      - hspec == 2.11.*
      - hspec-core == 2.11.*
      - http-client
      - http-client-tls
      - HUnit == 1.6.*
      - main-tester == 0.2.*
      - QuickCheck == 2.14.*
      - silently == 1.2.*
      - simplexmq
      - timeit == 2.0.*
      - unordered-containers
      - wai
      - wai-app-static
      - warp
      - warp-tls
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-A64M
      - -with-rtsopts=-N1

ghc-options:
  # - -haddock
  - -Weverything
  - -Wno-missing-exported-signatures
  - -Wno-missing-import-lists
  - -Wno-missed-specialisations
  - -Wno-all-missed-specialisations
  - -Wno-unsafe
  - -Wno-safe
  - -Wno-missing-local-signatures
  - -Wno-missing-kind-signatures
  - -Wno-missing-deriving-strategies
  - -Wno-monomorphism-restriction
  - -Wno-prepositive-qualified-module
  - -Wno-unused-packages
  - -Wno-implicit-prelude
  - -Wno-missing-safe-haskell-mode
  - -Wno-missing-export-lists
  - -Wno-partial-fields
  - -Wcompat
  - -Werror=incomplete-record-updates
  - -Werror=incomplete-patterns
  - -Werror=incomplete-uni-patterns
  - -Werror=missing-methods
  - -Werror=tabs
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wunused-type-patterns
  - -O2

default-extensions:
  - StrictData
