name: SimpleX Chat - smp-server

services:
  smp-server:
    image: ${SIMPLEX_IMAGE:-simplexchat/smp-server:latest}
    environment:
      WEB_MANUAL: ${WEB_MANUAL:-1}
      ADDR: ${ADDR?"Please specify the domain."}
      PASS: ${PASS:-}
    volumes:
      - ./smp_configs:/etc/opt/simplex
      - ./smp_state:/var/opt/simplex
    ports:
      - 5223:5223
    restart: unless-stopped
