#!/usr/bin/env sh
confd="/etc/opt/simplex"
logd="/var/opt/simplex/"

# Check if server has been initialized
if [ ! -f "$confd/smp-server.ini" ]; then
  # If not, determine ip or domain
  case $addr in
    '') printf "Please specify \$addr environment variable.\n"; exit 1 ;;
    *[a-zA-Z]*) set -- -n $addr ;;
    *) set -- --ip $addr ;;
  esac

  case $pass in
    '') set -- "$@" --no-password ;;
    *) set -- "$@" --password $pass ;;
  esac

  smp-server init -y -l "$@"
fi

# backup store log
[ -f "$logd/smp-server-store.log" ] && cp "$logd"/smp-server-store.log "$logd"/smp-server-store.log."$(date +'%FT%T')"

# Finally, run smp-sever. Notice that "exec" here is important:
# smp-server replaces our helper script, so that it can catch INT signal
exec smp-server start +RTS -N -RTS

