#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to DigitalOcean's SMP Server Droplet.
To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP), 5223 (SMP server).

Please read the instructions at
(TODO create instruction at https://marketplace.digitalocean.com/apps/simplex-chat)

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
