sequenceDiagram
  participant M as Existing<br>member (M)
  participant MA as Existing<br>member<br>agent (MA)
  participant A as Alice (A)
  participant AA as Alice's<br>agent (AA)
  participant BA as Bob's<br>agent (BA)
  participant B as Bob (B)

  note over A, AA: 1. create new group (no members)
  A ->> AA: gidA? GNEW groupInfo<br>(gidA - conn alias of this group for A)
  AA ->> A: gidA OK

  note over A, BA: 2. add Bob to group
  A ->> AA: gidA GADD idAB<br>(idAB - conn alias A has for B)
  
  AA ->> BA: via idAB: G_INV gidAB|_ groupInfo<br>(gidAB|_ - partial shared identifier for group for A and B<br>groupInfo contains current number of members etc.)
  BA ->> B: idBA GINV groupInfo
  B ->> BA: gidB? GJOIN
  BA ->> B: gidB OK
 
  BA ->> AA: via idBA: G_JOIN gidAB|BA<br>(idBA - conn alias B has for A,<br>gidAB|BA - shared identifier for group for A and B)
  AA -> A: gidA GCON idAB

  note over M, B: below steps happen for each existing member M

  AA ->> BA: via idAB: G_MEM gidAB|BA clvlAM midABM|_<br>(midABM|_ - partial member M id for A and B,<br>clvlAM - connection level, 0 - direct etc.)
  
  note over BA: create connection idBM
  
  BA ->> AA: via idBA: G_INV_MEM gidAB|BA midABM|BAM gidBM|_ idBMinv<br>(midABM|BAM - member M id for A and B<br>idBMinv - invitation to connect for member M)

  AA ->> MA: via idAM: G_MEM_INV gidAM|MA clvlAB midAMB|_ gidBM|_ idBMinv<br>(gidAM - how A identifies this member to M,<br>midAMB - how A identifies B to member M,<br>clvlAB - connection level, 0 - direct etc.)

  MA ->> BA: establish connection with idBM -> idMB

  MA ->> BA: via idMB: G_HELLO gidBM|MB
  MA ->> AA: via idMA: G_CON gidAM|MA midAMB|MAB (or G_ADD_ERR)
  MA ->> M: gidM GCON idMB

  BA ->> MA: via idBM: G_HELLO gidBM|MB
  BA ->> AA: via idBA: G_CON gidAB|BA midABM|BAM (or G_ADD_ERR)
  BA ->> B: gidB GCON idBM

  note over A, AA: once all members reported connection
  AA ->> A: gidA GALL idAB
  AA ->> BA: via idAB: G_ALL gidAB|BA midABM|BAM
  BA ->> B: gidB GALL idBM
  
  note over M, B: 3. B sends message to the group

  B ->> BA: gidB GSEND msg

  BA ->> AA: via idBA: G_MSG gidAB|BA msg
  AA ->> A: gidA GMSG idAB msg

  BA ->> MA: via idBM: G_MSG gidBM|MB msg
  MA ->> M: gidM GMSG idMB msg

  note over M, B: 4a. A leaves group

  A ->> AA: gidA GLEAVE
  AA ->> BA: via idAB: G_LEFT gidAB|BA
  BA ->> B: gidB: GLEFT idBA
  AA ->> MA: via idAM: G_LEFT gidAM|MA
  MA ->> M: gidM: GLEFT idMA

  note over M, B: 4b. A removes B from group
  A ->> AA: gidA GMDEL idAB
  AA ->> BA: via idAB: G_LEFT gidAB|BA 
  BA ->> B: gidB: GLEFT idBA

  note over M, B: below steps happen for each existing member M

  AA ->> MA: via idAM: G_MDEL gidAM|MA midAMB|MAB
  MA ->> AA: via idMA: G_MDELETED gidAM|MA midAMB|MAB
  MA ->> BA: via idMB: G_MDEL gidBM|MB
  MA ->> M: gidM: GMDELETED idMB
  BA ->> B: gidB: GMDELETED

  note over B, BA: once all members removed B

  BA ->> B: gidB: GEMPTY

  note over M, B: 4c. A deletes group
  A ->> AA: gidA GDEL
  AA ->> BA: via idAB: G_DEL gidAB|BA
  BA ->> B: gidB: GDELETED idBA
  AA ->> MA: via idAM: G_DEL gidAM|MA
  MA ->> M: gidM: GDELETED idMA
