sequenceDiagram
  participant M as Existing<br>member (M)
  participant MA as Existing<br>member<br>agent (MA)
  participant A as Alice (A)
  participant AA as Alice's<br>agent (AA)
  participant BA as Bob's<br>agent (BA)
  participant B as Bob (B)

  note over A, AA: 1. create new group (no members)
  A ->> AA: gidA? GNEW groupInfo<br>(gidA - conn alias of this group for A)
  AA ->> A: gidA OK

  note over A, BA: 2. add Bob to group
  A ->> AA: gidA GADD idAB<br>(idAB - conn alias A has for B)
  
  note over AA: create connection gidAB for B in group

  AA ->> BA: via idAB: G_INV gidABinv groupInfo
  BA ->> B: idBA GINV groupInfo
  B ->> BA: gidB? GJOIN
  BA ->> B: gidB OK

  note over AA: create connection gidBA for A in group
 
  BA ->> AA: via gidBA: G_JOIN
  AA -> A: gidA GCON idAB

  note over M, B: below steps happen for each existing member M

  AA ->> BA: via gidBA: G_MEM clvlAM midABM|_<br>(midABM|_ - partial member M id for A and B,<br>clvlAM - connection level, 0 - direct etc.)
  
  note over BA: create connection idBM for direct messages and<br> gidBM for M in group
  
  BA ->> AA: via gidBA: G_INV_MEM midABM|BAM gidBMinv idBMinv<br>(midABM|BAM - member M id for A and B<br>idBMinv - invitation to connect for member M)

  AA ->> MA: via gidAM: G_MEM_INV clvlAB midAMB|_ gidBMinv idBMinv<br>(midAMB - how A identifies B to member M,<br>clvlAB - connection level, 0 - direct etc.)

  MA ->> BA: establish connection with idBM -> idMB
  MA ->> BA: establish connection with gidBM -> gidMB

  MA ->> BA: via gidMB: G_HELLO
  MA ->> AA: via gidMA: G_CON midAMB|MAB (or G_ADD_ERR)
  MA ->> M: gidM GCON idMB

  BA ->> MA: via gidBM: G_HELLO
  BA ->> AA: via gidBA: G_CON midABM|BAM (or G_ADD_ERR)
  BA ->> B: gidB GCON idBM

  note over A, AA: once all members reported connection
  AA ->> A: gidA GALL idAB
  AA ->> BA: via gidAB: G_ALL midABM|BAM
  BA ->> B: gidB GALL idBA
  
  note over M, B: 3. B sends message to the group

  B ->> BA: gidB GSEND msg

  BA ->> AA: via gidBA: G_MSG msg
  AA ->> A: gidA GMSG idAB msg

  BA ->> MA: via gidBM: G_MSG msg
  MA ->> M: gidM GMSG idMB msg

  note over M, B: 4a. A leaves group

  A ->> AA: gidA GLEAVE
  AA ->> BA: via gidAB: G_LEFT
  BA ->> B: gidB: GLEFT idBA
  AA ->> MA: via gidAM: G_LEFT
  MA ->> M: gidM: GLEFT idMA

  note over M, B: 4b. A removes B from group
  A ->> AA: gidA GMDEL idAB
  AA ->> BA: via gidAB: G_LEFT
  BA ->> B: gidB: GLEFT idBA

  note over M, B: below steps happen for each existing member M

  AA ->> MA: via gidAM: G_MDEL midAMB|MAB
  MA ->> AA: via gidMA: G_MDELETED midAMB|MAB
  MA ->> BA: via gidMB: G_MDEL
  MA ->> M: gidM: GMDELETED idMB
  BA ->> B: gidB: GMDELETED

  note over B, BA: once all members removed B (or all left)

  BA ->> B: gidB: GEMPTY

  note over M, B: 4c. A deletes group
  A ->> AA: gidA GDEL
  AA ->> BA: via gidAB: G_DEL
  BA ->> B: gidB: GDELETED idBA
  AA ->> MA: via gidAM: G_DEL
  MA ->> M: gidM: GDELETED idMA
