sequenceDiagram
  participant A as Alice
  participant R as Current server<br>that has A's<br>receive queue
  participant R' as New server<br>that has the new A's<br>receive queue
  participant S as Server<br>that has A's send queue<br>(B's receive queue)
  participant B as Bob

  A ->> R': NEW: create new queue<br>(allow SKEY)
  A ->> S: SEND: QADD (R'): send address<br>of the new queue(s)
  S ->> B: MSG: QADD (R')
  B ->> R': SKEY: secure new queue
  B ->> R': SEND: QSEC: to agree shared secret
  R' ->> A: MSG: QSEC
  A ->> R: DEL: delete the old queue
  B ->> R': SEND: send messages to the new queue
  R' ->> A: MSG: receive messages from the new queue
  