# Base: https://github.com/haskell/actions/tree/main/setup#usage

name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest # TODO matrix testing
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Setup Stack
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.8.4'
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          enable-stack: true
          stack-version: 'latest'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}

      - name: Log SQLite default threading mode
        run: |
          sqlite3 test.db "pragma COMPILE_OPTIONS;" | grep THREADSAFE
          rm test.db

      - name: Build and run tests
        run: stack build --test
