name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        os: [ubuntu-latest]
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Setup Stack
        # https://github.com/haskell/actions/tree/main/setup
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.8.4'
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          enable-stack: true
          stack-version: 'latest'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}

      - name: Log SQLite default threading mode
        run: |
          sqlite3 test.db "pragma COMPILE_OPTIONS;" | grep THREADSAFE
          rm test.db

      - name: Build & test
        id: build_test
        run: |
          stack build --test
          echo "::set-output name=local_install_root::$(stack path --local-install-root)"

      - name: Echo $GITHUB_REF
        run: |
          echo $GITHUB_REF

      - name: Create pre-release
        # if: ${{ github.ref == 'refs/heads/master' }}
        if: ${{ github.ref == 'refs/heads/auto-pre-releases' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: 'latest'
          prerelease: true
          title: "dev build - ${{ runner.os }}"
          files: |
            LICENSE
            ${{ steps.build_test.outputs.local_install_root }}/bin/dog-food
