name: Build and push Docker image to Docker Hub

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push:
    name: Build and push Docker image
    strategy:
      fail-fast: false
      matrix:
        include:
          - app: smp-server
            app_port: "443 5223"
            arch: amd64
            runner: ubuntu-latest
            prefix: ""
          - app: smp-server
            app_port: "443 5223"
            arch: arm64
            runner: ubuntu-24.04-arm
            prefix: "arm64-"
          - app: xftp-server
            app_port: 443
            arch: amd64
            runner: ubuntu-latest
            prefix: ""
          - app: xftp-server
            app_port: 443
            arch: arm64
            runner: ubuntu-24.04-arm
            prefix: "arm64-"
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: simplex-chat/docker-login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata for Docker image
        id: meta
        uses: simplex-chat/docker-metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.app }}
          flavor: |
            latest=auto
            prefix=${{ matrix.prefix }}
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}

      - name: Build and push Docker image
        uses: simplex-chat/docker-build-push-action@v6
        with:
          push: true
          platforms: linux/${{ matrix.arch }}
          build-args: |
            APP=${{ matrix.app }}
            APP_PORT=${{ matrix.app_port }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
